dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2
  - frontend/src/bower_components
  - frontend/src/node_modules
  - integration/rocket-chat/node_modules

services:
  - mongodb

jdk:
  - openjdk8

before_install:
  - gem install sass
  - gem install compass
  - sudo apt-get update
  - sudo apt-get install -y rpm

install:
  - mvn -B clean install -Dquick

script:
  - mvn -B -DargLine="-Xmx2g" test

jobs:
  include:
    - stage: documentation
      if: branch IN (master, documentation) AND type IN (push, api)
      script: cd docs/target/html
                  && git init
                  && git config user.name $GH_USER_NAME
                  && git config user.email $GH_USER_EMAIL
                  && git add . && git commit -m "Update gh-pages after commit $TRAVIS_COMMIT to $TRAVIS_BRANCH"
                  && git push --force --quiet "https://$GH_TOKEN@$GH_REF" master:gh-pages > /dev/null 2>&1
    - stage: release
      if: tag =~ ^smarti- AND type = push
      script: mvn -B package -Pdeb,rpm -rf dist/
      deploy:
        provider: releases
        api_key:
          secure: qurrBs9JgJIze9tLkQ/0AXNbCqALhAmwAuAQ1n2RZAd3+rxrH+ktCWcXgh+sZtERmp49sMfvgZpfwgNM6o+UKugDMiK9FiSQhQrlMOk4Kg3kgzOB+af1th8t42Z83tnpNCPbyl5IfwFAeb+ruUmoDrdAMZZTlNuP9jCdrH+I4ZsyD1xWRcRR3yfYpyLfzwm41zY1qpOLdSLO3R20OnaiKoNDtvpGmRmiMZu1dvhVZv78Gy4Noy9gtPr7g3i/eXKc4wXUAdMsF+CaVfkLpEs4MrVfS+rAMxPdvj09s3bBUxwnkhIGgZV7pf1s9MOA8nUYz072uuzjbsEqee+zHC2EiID8lik5GZVZ/x6Frdhy382jGEcKUNy/mpKXy5ajx6Z154tOjYRbmM12WYesoXNEkMM6RFAx3FqF02k8a89uQhj+T5XXxFTNUQ1V5MkZBfGyOsqwCvGCQxBtvNdfKI1DZI6q725/8PBNKlqKhBveVtoek8UJGAWceNWRaf2K+w6Td1q6+9cvAH1nD/A+lcAjUP/DNzWo3fJCxzNLhHxZ04v+xCMM7aY9i3YlR9lyyp/pwO+cSHU6zvI5YT/SV9lFQOkyt/9MJ0HdCkAbX+l1ZG6G0YIOknEtcZ3snZwm4m8zBqS7pSHD272ub/oO7vBbTnzp3ng6fDarFcP2hOE61Ws=
        file_glob: true
        file:
          - dist/target/*.deb
          - dist/target/rpm/smarti/RPMS/noarch/*.rpm
        skip_cleanup: true
        name: ${TRAVIS_TAG}
        draft: true
        on:
          repo: redlink-gmbh/smarti
          tags: true
